Repository Blagoja95/DashNET, pull requests merged in 2023-12, with the labels that each got.

#13 #12 introducing .editorconfig file
  .editorconfig
Labels: enhancement

#14 #1: Init React
  README.md
  src/main/ui/package-lock.json
  src/main/ui/package.json
  src/main/ui/public/favicon.ico
  src/main/ui/public/index.html
  src/main/ui/public/manifest.json
  src/main/ui/src/App.js
  src/main/ui/src/index.js
Labels: enhancement

#15 #2: Included MUI framework
  src/main/ui/package-lock.json
  src/main/ui/package.json
  src/main/ui/src/App.js
Labels: enhancement

#17 16 : Initial React Structure, React Router and Redux
  src/main/ui/package-lock.json
  src/main/ui/package.json
  src/main/ui/src/App.js
  src/main/ui/src/components/layout/navigation/Navigation.js
  src/main/ui/src/components/pages/home/Home.js
  src/main/ui/src/components/ui/card/Card.js
  src/main/ui/src/index.js
  src/main/ui/src/store/controllers/uiController.js
  src/main/ui/src/store/slices/uiSlice.js
  src/main/ui/src/store/store.js
Labels: enhancement

#21 20: Create MUI Theme
  src/main/ui/src/index.js
Labels: enhancement

#25 #23 Introducing Header common component
  src/main/ui/src/App.js
  src/main/ui/src/components/layout/header/Header.js
  src/main/ui/src/components/pages/home/Home.js
  src/main/ui/src/index.js
Labels: enhancement

#26 19: Navigation Menu
  src/main/ui/src/App.js
  src/main/ui/src/components/layout/navigation/Navigation.js
  src/main/ui/src/components/pages/home/Home.js
Labels: enhancement

#34 #31 - Improved MUI dark theme
  src/main/ui/src/App.js
  src/main/ui/src/components/layout/header/Header.js
  src/main/ui/src/components/pages/home/Home.js
  src/main/ui/src/index.js
  src/main/ui/src/theme/dark/dark.js
Labels: enhancement

#32 #27 - All tasks grid init
  src/main/ui/src/components/layout/header/Header.js
  src/main/ui/src/components/layout/navigation/Navigation.js
  src/main/ui/src/components/pages/home/Home.js
  src/main/ui/src/components/ui/avatar/UserAvatar.js
  src/main/ui/src/components/ui/grid/Grid.js
  src/main/ui/src/theme/dark/dark.js
Labels: enhancement

#18 #4 - Docker compose
  .dockerignore
  README.md
  React.Dockerfile
  Spring.Dockerfile
  docker-compose.yml
  pom.xml
Labels: documentation, enhancement, Build

#38 Search dialog component
  src/main/ui/src/App.js
  src/main/ui/src/components/layout/header/Header.js
  src/main/ui/src/components/layout/search/Search.js
  src/main/ui/src/components/layout/search/debounced/Debounced.js
  src/main/ui/src/components/layout/search/searchRecord/SearchRecord.js
  src/main/ui/src/components/pages/home/Home.js
  src/main/ui/src/store/slices/uiSlice.js
  src/main/ui/src/theme/dark/dark.js
Labels: enhancement

#47 Improving Docker dev
  README.md
  Spring.Dockerfile
  docker-compose.yml
Labels: documentation, enhancement, Build, WIP

#53 51 create setting page
  src/main/ui/src/App.js
  src/main/ui/src/components/pages/settings/ChangePassword.js
  src/main/ui/src/components/pages/settings/InputGroup.js
  src/main/ui/src/components/pages/settings/Profession.js
  src/main/ui/src/components/pages/settings/Settings.js
  src/main/ui/src/components/pages/settings/UserAvatar.js
  src/main/ui/src/components/pages/settings/UserInformation.js
  src/main/ui/src/theme/dark/dark.js
Labels: enhancement

#59 #6: Introducing `.env.example` file
  .env.example
  .gitignore
  docker-compose.yml
  src/main/resources/application.properties
Labels: enhancement
